title: Oleh Aloshkin
logo: /assets/img/me.jpg
description: Front-end developer. ğŸ“ Vienna, Austria &nbsp;<a href="https://docs.google.com/document/d/1DjYxJO8-VJaqUbTAdtSgjQdl2HRaF1xV9RZlBHe7mbI/edit?usp=sharing">CV</a>
google_analytics: UA-86724647-2
theme: jekyll-theme-minimal
